# Generated by Django 3.0 on 2020-06-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200617_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
